# Generated by Django 5.2.9 on 2025-12-04 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_lists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('due_date', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False, verbose_name='complete')),
                ('todo_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='todo_lists.todolist')),
            ],
        ),
        migrations.AddConstraint(
            model_name='todolist',
            constraint=models.UniqueConstraint(models.F('user'), models.F('name'), name='unique_user_name'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(models.F('todo_list'), models.F('name'), name='unique_todo_list_name'),
        ),
    ]
