# Generated by Django 6.0 on 2026-01-02 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_lists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_completed',
        ),
    ]
